### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by lehuan5062** [readyplayerme/rpm-unreal-avatar-creator#34]
**Is your feature request related to a problem? Please describe.**
Multiplayer.

**Describe the solution you'd like**
Replication for the avatar creator widget.

**Comment by gadamyan** [comment]
Hi. Widgets can not have replication. Could you please describe the use case in detail?

**Comment by lehuan5062** [comment]
I would like to have multiple players to join a session and require them to create an avatar. The created avatar should be replicated.
I used WebView for that task and completed.
When I use AvatarCreator, the UI keep loading the wrong body type.

**Comment by gadamyan** [comment]
What do you mean by wrong body type? Do you mean half body is shown inside the widget instead of the full body? Could you make a screenshot? BTW there is a possibility to skip the body type selection screen by providing a constructor parameter when creating the widget. Those parameters are described in the [readme](https://github.com/readyplayerme/rpm-unreal-avatar-creator#use-the-sample-project)

**Comment by lehuan5062** [comment]
I will provide the video when I have the time, maybe after a week.

**Comment by lehuan5062** [comment]
I don't think I have time for a video, but it was actually happened, so I switched to use WebView instead. Or maybe I did the multiplayer code wrong. Let's close this issue.
